# Generated by Django 2.1.1 on 2018-10-03 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automovel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15, verbose_name='CO')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ServicoDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_inicial', models.BigIntegerField(verbose_name='Kilometros iniciais')),
                ('km_final', models.BigIntegerField(blank=True, null=True, verbose_name='Kilometros finais')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observção')),
                ('estado_concluido', models.BooleanField(verbose_name='Serviço concluído')),
                ('validar_servico', models.BooleanField(verbose_name='Validar servico')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('automovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Automovel', to='automovel.Automovel')),
                ('co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico_diario.CO')),
                ('condutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condutor', to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Servico', to='servico.Servico')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'servico diario',
                'verbose_name_plural': 'servicos diarios',
            },
        ),
    ]
