# Generated by Django 2.1.1 on 2018-09-28 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico_diario', '0004_auto_20180928_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicodiario',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='servico_diario.Categoria'),
        ),
    ]
