# Generated by Django 2.1.1 on 2018-09-28 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico_diario', '0006_auto_20180928_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicodiario',
            name='co',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co', to='servico_diario.CO'),
        ),
    ]
