# Generated by Django 2.1.1 on 2018-09-18 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_condustor',
            new_name='is_condutor',
        ),
    ]
