# Generated by Django 2.1.1 on 2018-10-04 00:08

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('automovel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='automovel',
            table='automovel',
        ),
    ]
