# Generated by Django 2.1.1 on 2018-09-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0002_auto_20180918_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovel',
            name='data_matricula',
            field=models.DateField(blank=True, null=True, verbose_name='Data matricula'),
        ),
    ]
