# Generated by Django 2.1.1 on 2018-09-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0003_auto_20180918_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovel',
            name='valor_do_seguro_anual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor anual do seguro anual'),
        ),
    ]
