# Generated by Django 2.1.1 on 2018-09-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0003_auto_20180921_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovel',
            name='cartrack',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cartrack'),
        ),
        migrations.AlterField(
            model_name='automovel',
            name='matricula',
            field=models.CharField(max_length=20, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='automovel',
            name='seguro',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Seguro'),
        ),
    ]
