# Generated by Django 2.1.1 on 2018-09-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0005_auto_20180918_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovel',
            name='prestacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prestação'),
        ),
    ]
