# Generated by Django 2.1.1 on 2018-09-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0005_auto_20180921_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovel',
            name='contrato',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Contrato'),
        ),
    ]
