# Generated by Django 2.1.1 on 2018-09-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0007_auto_20180921_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovel',
            name='banco_de_pagamento',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Banco de pagamento'),
        ),
        migrations.AlterField(
            model_name='automovel',
            name='combustivel',
            field=models.CharField(max_length=40, verbose_name='Combustivel'),
        ),
        migrations.AlterField(
            model_name='automovel',
            name='contrato',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='automovel',
            name='financeira',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Financeira'),
        ),
    ]
