# Generated by Django 2.1.1 on 2018-09-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0008_auto_20180921_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovel',
            name='modelo',
            field=models.CharField(max_length=80, verbose_name='Modelo'),
        ),
    ]
