# Generated by Django 2.1.1 on 2018-09-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automovel', '0008_auto_20180918_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automovel',
            name='valor_actual_do_veiculo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Valor actual do veiculo'),
        ),
    ]
