# Generated by Django 2.1.1 on 2018-09-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurso_humano', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursohumano',
            name='nome',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='recursohumano',
            name='obs',
            field=models.CharField(max_length=50, verbose_name='OBS'),
        ),
    ]
