# Generated by Django 2.1.1 on 2018-09-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurso_humano', '0002_auto_20180921_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursohumano',
            name='nome',
            field=models.CharField(max_length=60, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='recursohumano',
            name='nome_completo',
            field=models.CharField(max_length=60, verbose_name='Nome completo'),
        ),
    ]
