# Generated by Django 2.1.1 on 2018-09-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='zona',
            field=models.CharField(max_length=10, verbose_name='Zona'),
        ),
    ]
