# Generated by Django 2.1.1 on 2018-09-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0003_auto_20180921_0141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['zona']},
        ),
        migrations.AddField(
            model_name='servico',
            name='banca',
            field=models.PositiveIntegerField(null=True, verbose_name='Banca'),
        ),
    ]
